[project]
name = "Emotion detection using CNN"
version = "0.1.0"
description = "Real time facial emotion recognition using CNN and opencv"
authors = [
    {name = "Yasas Sri", email = "ezioelijahhanaang@gmail.com"}
]
requires-python = ">=3.9"
